travis:
  secure:
    BINSTAR_TOKEN: mZ+kwEjzp6QfsmFLGrjfwZhdWwNs4GOiu9Ctrfhea47VsOl9HuSg2KoKU+WR2tup3h9+poTa4xijiMBiY2sLY621acPNQdS1oVXLQg4EOpa8nlUPb1hx6Odp4q7B3txzhDZlhkGjwh0qYWAhBLCZO3XyikgXkrz4vhKU99nW7OkQxfJUoNL/YURhg+dxf9WllGcRCTRA8JueHxTxpc+Oj+KQNnQ2q9AGbUb8Ewd9hvyHb3hlR8fFOxWgZApcXyWksydZn0mORafAl8aPUuw24SYgRHQUX8Eo2dY2knteD1Pe3w2NTqpKgWaAdrmPrhlEJNwIprgGt3JRXImLfXGV7If6PEg3BUMrrxArRqa03ixp17FicL5/QACyGirXdqReJGyRn/sJUJPAwVPApRMY0RubTzUOrsprNasrULHruXAPTmGkvJsZ56zkgOqfYfs4I4UppF7y34yIhwl0Bxxdf/0vQ0fn2gbIieZfghm9KLRUvevKQmVtd5idwvbJp1UhRuoChVVGn9T8bR27WRnXfOBlpaJAPPZlT458zmaJOO2ljYStGqU8aA8wmOPGu6hxY6zfWO+Ktd7WIURLVD0DCeLF6mlPbHhKDH9kjU9mpj0m262mes2O/vulOLukN58m5nfXjbIkxE6PBxBa5JfCMGRZ2XNHLqVmjFlW9KR64Wo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
