travis:
  secure:
    BINSTAR_TOKEN: ah1NdwcbkLt2HL0ZoxeiwrYu3eFm7FB3VWuuxXAL2G2NN7vlymmLy6BJWgG3iY6YM6UI05YaDPy89SmoKT+2/aGvto/V83HaTnGhqCwEFs27+JKmhdaQI++L2KULZqm6EyA677XJdYZsxM6/ZL7lU2WcukFNAA+CiybJu/ZQh97iEv+iTCValtGz3Usq6gBVmpp7FR/8pizp+LRetu+Vpj7gBfdw/QlXt0FaILcoauG2+pYq/xpIosdbgrPlhE7Pgb0c2C0dFciDFZX/Zz9XMORvThU6mo+8hcEP/8Tn6b62EBWuIdcD428QyDW6NS20afdxJTE4bl3TjqPq32bSwXudnCuGHViFlnC7jcWkV0bSc2Wv/z0FtfOYSzz5s2iakWeW0e+3esCTXg3pT2MJSTwU2sN8v4ZSxtMsDOIdl9W1gRzIhI22HCzy8/Ls9QnLQYluN/VwrRPxrMVVFxtWISTDIwEgr5PJJu645v96mj9A0l4HWoR/zh+mrgxMDtD6VZ/1XQAM2vu16ccMkPA/1imRtH2HabpYRah1EzKzFI1mNfXAG6MKQIB+1oDgxSDwln2amzdNprZvpdiMCr3TBe1HJJOzo7Y8lBmVHLXkOL/ejYNQ94K/GZWVvVS6ICN8eoX+Xfz6zGsTjzlQrB/0lUx2KtqUFP1lxKpf1ogbirg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
